### ISSUE TITLE
Sending msg.action "close" causes to raise error with "connection lost" & catch not working on this tcp-client

### ISSUE THREAD

**Issue by TiHerbatka** [jorgen-k/node-red-contrib-tcp-client2#3]
Hi,
When sending msg.action "close" my NR instance is raising error in debug window with "connection lost".

And also (might be not related) catch node is not actually catching any errors when they are rised in the debug window.
Not catching erros was tested:
- Sending msg.action "close" - debug window shows error but there are no actual errors catched by "catch" node.
- Cutting off connection on the tcp server side - i've literally disabled the tcp server, tcp-client tried to reconnect but at the end threw an error but only in debug window (not an actual error I guess).
-

**Comment by jorgen-k** [comment]
I find two faults in the question. 

1. Confirmed errouneous ”connection lost” message, left from development, should be debug with correct wording ”connection objet lost”. Will be fixed.

2 I can confirm that no errors are thrown, so the catch node cannot catch. This we will fix. However during retries no error will be thrown, only if retry limit is exceeded, does this seem fair to you?
